---
- name: Include credentials file if exists
  include_vars: credentials.yml
  ignore_errors: yes
  tags:
    - always

- name: Validate API action
  assert:
    that:
      - useralias is defined
      - newpass is defined
  tags:
    - always

- name: API | Select API server
  set_fact:
    apiserver: "{{ groups[servers_group_name] | map('extract', hostvars, ['ansible_host']) | first }}"
  when: apiserver is not defined
  tags:
    - api
    - api-login

- name: API | Login
  uri:
    url: "https://{{ apiserver }}/zabbix/api_jsonrpc.php"
    body_format: json
    validate_certs: no
    body:
      jsonrpc: "2.0"
      method: 'user.login'
      params:
        user: '{{ apiuser | default("Admin") }}'
        password: '{{ apipass | default(adminpass) | default("zabbix") }}'
      id: 1
  register: apiauthresult
  failed_when: apiauthresult.failed or apiauthresult.json.error is defined
  tags:
    - api
    - api-login


- block:
    - name: 'API | Get user "{{ useralias }}"'
      uri:
        url: "https://{{ apiserver }}/zabbix/api_jsonrpc.php"
        body_format: json
        validate_certs: no
        body:
          jsonrpc: "2.0"
          method: 'user.get'
          params:
            filter:
              alias: '{{ useralias }}'
            limit: 1
          id: "{{ apiauthresult.json.id }}"
          auth: "{{ apiauthresult.json.result }}"
      register: apiresult
      failed_when: apiresult.failed or apiresult.json.error is defined
      tags:
        - api
        - api-getuser

    - name: 'API | Change password for "{{ useralias }}"'
      uri:
        url: "https://{{ apiserver }}/zabbix/api_jsonrpc.php"
        body_format: json
        validate_certs: no
        body:
          jsonrpc: "2.0"
          method: 'user.update'
          params:
            userid: '{{ apiresult.json.result[0].userid }}'
            passwd: '{{ newpass }}'
          id: "{{ apiauthresult.json.id }}"
          auth: "{{ apiauthresult.json.result }}"
      register: apiresult
      failed_when: apiresult.failed or apiresult.json.error is defined
      tags:
        - api
        - api-changeuserpasswd

  always:
    - name: API | Logout
      uri:
        url: "https://{{ apiserver }}/zabbix/api_jsonrpc.php"
        body_format: json
        validate_certs: no
        body:
          jsonrpc: "2.0"
          method: 'user.logout'
          params: []
          id: 1
          auth: "{{ apiauthresult.json.result }}"
      register: apiauthresult
      failed_when: apiauthresult.failed or apiauthresult.json.error is defined
      tags:
        - api
        - api-logout
