#
# Zabbix Server Installation
#

- name: 'Install deb from {{ zabbix_deb_url }}'
  apt:
    deb: "{{ zabbix_deb_url }}"
  tags:
    - install-server
    - install-server-install
    - install-server-install-packages

- name: Install Zabbix Server packages
  apt:
    pkg:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-agent
      - default-mysql-client
      - python3-mysqldb
    update_cache: yes
  tags:
    - install-server
    - install-server-install
    - install-server-install-packages

- name: Include credentials file if exists
  include_vars: credentials.yml
  ignore_errors: yes
  tags:
    - always

- name: Create database
  mysql_db:
    name: "{{ dbname }}"
    encoding: utf8
    collation: utf8_bin
    state: present
  register: db_created
  tags:
    - install-server
    - install-server-install
    - install-server-install-database

- name: Create dbuser and grant privileges
  mysql_user:
    name: '{{ dbuser }}'
    host: localhost
    password: '{{ dbpass }}'
    priv: '{{ dbname }}.*:ALL,GRANT'
    state: present
  tags:
    - install-server
    - install-server-install
    - install-server-install-database

- name: Import database skeleton
  mysql_db:
    state: import
    name: '{{ dbname }}'
    target: '{{ dbdata_dumpfile }}'
  when: db_created.changed
  tags:
    - install-server
    - install-server-install
    - install-server-install-database

- name: Configure Zabbix Server
  lineinfile:
    dest: "{{ item.configfile }}"
    regexp: "^{{ item.param }}="
    insertafter: "^# {{ item.param }}=$"
    line: "{{ item.param }}={{ item.value }}"
  notify:
    - 'Restart {{ item.service }}'
  with_items:
    - {configfile: "/etc/zabbix/zabbix_server.conf", param: "DBName", value: "{{ dbname }}", service: 'zabbix-server'}
    - {configfile: "/etc/zabbix/zabbix_server.conf", param: "DBUser", value: "{{ dbuser }}", service: 'zabbix-server'}
    - {configfile: "/etc/zabbix/zabbix_server.conf", param: "DBPassword", value: "{{ dbpass }}", service: 'zabbix-server'}
    - {configfile: "/etc/zabbix/zabbix_agentd.conf", param: "Hostname", value: "{{ inventory_hostname }}", service: 'zabbix-agent'}
  loop_control:
    label: '{{ item.service }}: {{ item.param }}'
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-zabbix

- name: Set php timezone
  replace:
    path: /etc/zabbix/apache.conf
    regexp: '(#\s*)?php_value date.timezone .*$'
    replace: 'php_value date.timezone {{ timezone }}'
  notify:
    - Restart apache2
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-apache2

- name: Enable Apache2 stuff
  command: |
    {{ item.exec }} {{ item.name }}
  register: cmdresult
  changed_when: cmdresult.stdout is search('Enabling')
  when: enablessl
  notify:
    - Restart apache2
  with_items:
    - {exec: /usr/sbin/a2enmod, type: module, name: ssl}
    - {exec: /usr/sbin/a2ensite, type: site, name: default-ssl}
    - {exec: /usr/sbin/a2enmod, type: module, name: rewrite}
  loop_control:
    label: "'{{ item.name }}' {{ item.type }}"
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-apache2

- name: Enable HTTP to HTTPS redirection
  blockinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    insertafter: '<VirtualHost.*80>'
    block: |
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{HTTPS} off
            RewriteRule /(.*) https://%{SERVER_NAME}/$1 [R,L]
          </IfModule>
  when: enablessl
  notify:
    - Restart apache2
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-apache2

- name: Redirect / to /zabbix/
  lineinfile:
    dest: /etc/apache2/sites-enabled/default-ssl.conf
    regexp: 'RedirectMatch \^/\$ '
    insertafter: '<VirtualHost .*443>'
    line: RedirectMatch ^/$ /zabbix/
  when: redirectalias
  notify:
    - Restart apache2
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-apache2

- name: Configure Zabbix Frontend
  template:
    src: zabbix.conf.php.j2
    dest: /usr/share/zabbix/conf/zabbix.conf.php
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-frontend

- meta: flush_handlers
  tags:
    - always

- name: Set Admin Password Reset Vars
  set_fact:
    useralias: Admin
    newpass: "{{ adminpass }}"
    apipass: "{{ apipass | default('zabbix' if (db_created is defined and db_created.changed) else adminpass) }}"
  when: adminpass is defined
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-management
    - install-server-configure-changeadminpasswd

- include_tasks:
    file: 'change-user-passwd.yml'
    apply:
      tags:
        - install-server
        - install-server-configure
        - install-server-configure-management
        - install-server-configure-changeadminpasswd
  when: adminpass is defined
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-management
    - install-server-configure-changeadminpasswd

- name: Update API Management Credentials
  set_fact:
    apiuser: Admin
    apipass: "{{ adminpass }}"
  when: adminpass is defined
  tags:
    - install-server
    - install-server-configure
    - install-server-configure-management
