---
# handlers file for ansible-role-zabbix

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: Restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes

